config_version = 14

[bar.default]
center = [ "workspaces" ]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "clock",
    "session"
]
font_family = "Hack Nerd Font Propo"
margin_ends = 0
scale = 1.4000000134110451
start = [ "launcher", "control-center", "wallpaper" ]

[brightness]
enable_ddcutil = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[theme]
builtin = "Tokyo-Night"
mode = "light"
shell_mode = "dark"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "qt" ]

[wallpaper]
directory = "/home/metalneox/Background"
directory_dark = "/home/metalneox/Background"
directory_light = "/home/metalneox/Background"

    [wallpaper.default]
    path = "/home/metalneox/Background/warcraft_mage.jpeg"

    [wallpaper.last]
    path = "/home/metalneox/Background/warcraft_mage.jpeg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/metalneox/Background/warcraft_mage.jpeg"

[widget.brightness]
enabled = false

[widget.control-center]
enabled = false

[widget.network]
enabled = false